modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="newworld" #mandatory
version="0.1" #mandatory
displayName="New World" #mandatory
updateJSONURL="https://github.com/FlamingSharky/DarkAgesExpedition"
displayURL="Dark Ages Expedition Curseforge Page"
logoFile="logo.png" #optional
credits="I just wrote the scripts, AvocadoSpud is the actual owner." #optional
authors="Sharky, AvocadoSpud" #optional
description='''
Just a mod, adds the wooden meadow biome
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.newworld]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.newworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
